site:
  title: Neo4j GraphAcademy
  start_page: training-welcome::index.adoc

content:
  sources:
    - url: .
      branches: 'HEAD'
      start_paths:
      - 'modules/home'
      - 'modules/4.0-intro-neo4j'
      - 'modules/graph-data-modeling'
      - 'modules/4.0-implementing-graph-data-models'
      - 'modules/4.0-neo4j-admin'
      - 'modules/4.0-cypher-query-tuning'
      - 'modules/4.0-intro-graph-algos'
      - 'modules/online-training-v2'
      - 'modules/neo4j-administration'
      - 'modules/gds-applied-algos'
      - 'modules/datascience'
      - 'modules/applied-algos'

output:
  dir: ./public/

ui:
  bundle:
    url: https://github.com/neo4j-documentation/docs-refresh/raw/master/ui/build/ui-bundle.zip
    snapshot: true

urls:
  html_extension_style: indexify

asciidoc:
  attributes:
    experimental: ''
    page-component: training
    page-theme: training
    page-canonical-root: /training-welcome
    page-breadcrumbs:
      - name: Neo4j Training
        url: /training-welcome
